### ISSUE TITLE
[Question] Faster Iteration

### ISSUE THREAD

**Issue by boan-anbo** [retorquere/generator-zotero-plugin#25]
Thanks so much for the great generator. 

I just have a side question: what's your best practice for faster iteration during development?

I have been manually removing and re-installing the built .xpi over and over and that is obviously not optimal. Any suggestions would be appreciated!

**Comment by retorquere** [comment]
I've included a script I use for this in [zotero-plugin](https://github.com/retorquere/zotero-plugin) which you already have installed (but will need to update to get the start script).

**Comment by boan-anbo** [comment]
Can't believe I didn't know abt the repo. Thank you so much for your work!

**Comment by retorquere** [comment]
No way you could have known, they provide utility scripts that the generator installs automatically, and you don't call them manually.

And welcome!
