### ISSUE TITLE
Question/maybe bug: value of releaseURL seems incorrect

### ISSUE THREAD

**Issue by wbthomason** [retorquere/generator-zotero-plugin#5]
I'm encountering an error related to the value of `releaseURL`, and I'm uncertain if it's user error or a bug.

Specifically: The default value of `releaseURL` is `https://github.com/<username>/<repo>/releases/download/release/`. First off, this URL does not exist, but perhaps this is intended? When this URL is used in https://github.com/retorquere/zotero-plugin-webpack/blob/eefb59c1d63b4a5d024e76d5bf2d0968b5decf08/bin/release.ts#L141, it causes `getRelease` (https://github.com/retorquere/zotero-plugin-webpack/blob/eefb59c1d63b4a5d024e76d5bf2d0968b5decf08/bin/release.ts#L108) to try to get a release tagged "release", which does not exist and causes `update_rdf` to fail.

I'm not sure if I was meant to customize the value of `releaseURL` (and, if so, to what), or if this is a bug?

Also, thanks very much for the excellent scaffolding plugin; it made my life much easier.

**Comment by retorquere** [comment]
Hi, this was just underdocumented; I've published an updated version of https://github.com/retorquere/zotero-plugin-webpack (which is what uses the releaseURL in the end) so that it will created the missing releases automatically; the README on that repo has been updated to describe the behavior. You should be able to upgrade the lot using `ncu -u` (https://www.npmjs.com/package/npm-check-updates, use with care though). I usually created those two special releases manually, but this is easier.

**Comment by wbthomason** [comment]
Thanks! Sorry, but I think I'm still doing something wrong - I updated to the latest `zotero-plugin-webpack` and tried to issue a version bump build, but now I get the error "Building tag release, but package version is 0.1.1" from `zotero-plugin-release`. It looks like the `update.rdf` was created correctly, though, so maybe this build failure doesn't matter and can just be ignored? The `release` tag does not have an associated `.xpi`, but, again, perhaps this is intended if it's only meant to hold the `update.rdf` file?

Thank you for the help and plugin; sorry for my confusion.

**Comment by retorquere** [comment]
No worries. It means that the version in `package.json` does not match the version that was tagged and built on Travis. How do you bump versions? Looking at your travis-ci.com builds it looks like 0.1.2 built successfully. If travis is set up, `npm version <patch|minor|major>` should do the job.

**Comment by wbthomason** [comment]
Ah, that might be it - I'm not very familiar with `npm`/Node tooling generally, so I was manually making and pushing tags with git. I'll use `npm version` in the future.

And yep, looking at `update.rdf`, it seems like everything is good to go (it updated to point to v0.1.2). Thank you again!

**Comment by retorquere** [comment]
No worries, nothing of this was documented, so you left it better than you found it.
